
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 324234-deployment
  labels:
    app: 324234
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 324234
  template:
    metadata:
      labels:
        app: 324234
    spec:
      containers:
        - name: 234234234234234
          image: 23423
          imagePullPolicy: Always
      imagePullSecrets:
        - name: myregistrykey
    