
apiVersion: v1
kind: Service
metadata:
    name: 324234-service
    labels:
        app: 324234
spec:
    type: NodePort
    selector:
        app: 324234  # Replace with your application's label
    ports:
        - port: 324234        # The port your application listens on internally
          targetPort: 3423423  # The port within the pod
          nodePort: 234234
          protocol: TCP
    