
apiVersion: apps/v1
kind: Deployment
metadata:
  name: businessservice-deployment
  labels:
    app: businessservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: businessservice
  template:
    metadata:
      labels:
        app: businessservice
    spec:
      containers:
        - name: businessservice
          image: 212.85.1.77:5000/businessservice:latest
          imagePullPolicy: Always
      imagePullSecrets:
        - name: myregistrykey
    