
services:

#start dbBusiness
  dbBusiness: 
    image: postgres 
    container_name: dbBusiness 
    restart: always 
    ports: 
      - 5438:5432 
    volumes: 
      - /myschool/data:/var/lib/postgresql 

#end dbBusiness
#[content]
        
networks:
  web:
    external: false
